apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-database-k8s
  name: test-database-k8s
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-database-k8s
  type: ClusterIP
status:
  loadBalancer: {}
